In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from epiweeks import Week
import matplotlib.pyplot as plt

In [2]:
label = 'forecast_dengue_city'

caminho_da_pasta = Path("./predictions/")

padrao_arquivo = f"{label}_*.csv.gz"  # Altere para o seu termo

arquivos_encontrados = list(caminho_da_pasta.glob(padrao_arquivo))

arquivos_encontrados

[PosixPath('predictions/forecast_dengue_city_3rd_imdc_unesp_recogna_daniel.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_emap_lstm_muni.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_nus_nus-cerm.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_isi_isi-dengue.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_emap_epidematicos_sarimax_fixed.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_fgv_pattern-blue.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_emap_xgbsillas.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_purdue_neuralearth.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_emap_epidematicos_prophet_fixed.csv.gz')]

In [3]:
print(len(arquivos_encontrados))

9

In [4]:
arquivos_ignorados = {
    f"{label}_3rd_imdc_emap_epidematicos_prophet.csv.gz",
    f"{label}_3rd_imdc_emap_epidematicos_sarimax_muni.csv.gz",
    f"{label}_3rd_imdc_emap_epidematicos_sarimax_state.csv.gz",
}

arquivos_encontrados = [
    arquivo
    for arquivo in caminho_da_pasta.glob(padrao_arquivo)
    if arquivo.name not in arquivos_ignorados
]

arquivos_encontrados

[PosixPath('predictions/forecast_dengue_city_3rd_imdc_unesp_recogna_daniel.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_emap_lstm_muni.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_nus_nus-cerm.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_isi_isi-dengue.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_emap_epidematicos_sarimax_fixed.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_fgv_pattern-blue.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_emap_xgbsillas.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_purdue_neuralearth.csv.gz'),
 PosixPath('predictions/forecast_dengue_city_3rd_imdc_emap_epidematicos_prophet_fixed.csv.gz')]

In [5]:
print(len(arquivos_encontrados))

9

In [7]:
list_dfs = []

for arq in arquivos_encontrados:

    df_ = pd.read_csv(arq)
    df_.date = pd.to_datetime(df_.date)
    df_['model'] = str(arq)[33:-7]

    df_ = df_.loc[(df_.date>= pd.to_datetime(Week(2026, 41).startdate())) & (df_.date<= pd.to_datetime(Week(2027, 40).startdate()))]

    list_dfs.append(df_)


df_end = pd.concat(list_dfs, ignore_index = True)

df_end.to_csv(f'./predictions/forecast_all_models_{label[9:]}.csv.gz')


df_end.head()

,date,lower_95,lower_90,lower_80,lower_50,pred,upper_50,upper_80,upper_90,upper_95,adm_2,id,validation,model
0,2026-10-11,2.890082,4.104696,5.981742,10.796253,20.098450,36.736100,62.758392,86.202965,113.43069,2931350,14553,Forecast,3rd_imdc_unesp_recogna_daniel
1,2026-10-18,2.731982,3.897232,5.697991,10.316830,19.240970,35.202442,60.167120,82.658860,108.77998,2931350,14553,Forecast,3rd_imdc_unesp_recogna_daniel
2,2026-10-25,2.586092,3.705791,5.436156,9.874439,18.449718,33.787220,57.776012,79.388520,104.48848,2931350,14553,Forecast,3rd_imdc_unesp_recogna_daniel
3,2026-11-01,2.475223,3.560305,5.237173,9.538239,17.848400,32.711723,55.958862,76.903180,101.22715,2931350,14553,Forecast,3rd_imdc_unesp_recogna_daniel
4,2026-11-08,2.369077,3.421016,5.046666,9.216360,17.272700,31.682049,54.219112,74.523710,98.10477,2931350,14553,Forecast,3rd_imdc_unesp_recogna_daniel

In [ ]:
3rd_imdc_lncc_surge_model26_chikungunya

In [16]:
df_end.model.unique()

<ArrowStringArray>
['3rd_imdc_emap_epidematicos_sarimax_fixed',
          '3rd_imdc_lncc_ARp26_chikungunya',
      '3rd_imdc_lncc_clidengo26chikungunya',
                    '3rd_imdc_nus_nus-cerm',
 '3rd_imdc_emap_epidematicos_prophet_fixed',
                  '3rd_imdc_procc_bb_model',
              '3rd_imdc_purdue_neuralearth',
                 'mosqlimate-ai-competitor',
                       '3rd_imdc_emap_lstm',
                  '3rd_imdc_emap_xgbsillas',
                          'DS-OKSTATE-2026',
  '3rd_imdc_lncc_surge_model26_chikungunya']
Length: 12, dtype: str

In [ ]:
df_ = pd.read_csv("predictions/forecast_dengue_state_3rd_imdc_afya_ric.csv.gz")
df_.head()

,date,lower_95,lower_90,lower_80,lower_50,pred,upper_50,upper_80,upper_90,upper_95,adm_1,id,validation
0,2026-06-07,0.0,0.0,0.0,344.0,775.0,1206.0,1594.0,1826.0,2028.0,33,14168,Forecast
1,2026-06-14,0.0,0.0,0.0,0.0,652.0,1406.0,2084.0,2490.0,2843.0,33,14168,Forecast
2,2026-06-21,0.0,0.0,0.0,0.0,547.0,1604.0,2556.0,3125.0,3619.0,33,14168,Forecast
3,2026-06-28,0.0,0.0,0.0,0.0,336.0,1669.0,2869.0,3587.0,4210.0,33,14168,Forecast
4,2026-07-05,0.0,0.0,0.0,0.0,328.0,1912.0,3338.0,4191.0,4931.0,33,14168,Forecast