In [9]:
import numpy as np
import pandas as pd
from pathlib import Path
from epiweeks import Week
import matplotlib.pyplot as plt

In [10]:
label = 'forecast_chik_state'

caminho_da_pasta = Path("./predictions/")

padrao_arquivo = f"{label}_*.csv.gz"  # Altere para o seu termo

arquivos_encontrados = list(caminho_da_pasta.glob(padrao_arquivo))

arquivos_encontrados

[PosixPath('predictions/forecast_chik_state_3rd_imdc_emap_epidematicos_sarimax_fixed.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_lncc_ARp26_chikungunya.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_lncc_clidengo26chikungunya.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_nus_nus-cerm.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_emap_epidematicos_prophet_fixed.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_procc_bb_model.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_purdue_neuralearth.csv.gz'),
 PosixPath('predictions/forecast_chik_state_mosqlimate-ai-competitor.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_emap_lstm.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_emap_xgbsillas.csv.gz'),
 PosixPath('predictions/forecast_chik_state_DS-OKSTATE-2026.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_lncc_surge_model26_chikungunya.csv.gz')]

In [11]:
print(len(arquivos_encontrados))

12

In [12]:
arquivos_ignorados = {
    f"{label}_3rd_imdc_emap_epidematicos_prophet.csv.gz",
    f"{label}_3rd_imdc_emap_epidematicos_sarimax_muni.csv.gz",
    f"{label}_3rd_imdc_emap_epidematicos_sarimax_state.csv.gz",
}

arquivos_encontrados = [
    arquivo
    for arquivo in caminho_da_pasta.glob(padrao_arquivo)
    if arquivo.name not in arquivos_ignorados
]

arquivos_encontrados

[PosixPath('predictions/forecast_chik_state_3rd_imdc_emap_epidematicos_sarimax_fixed.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_lncc_ARp26_chikungunya.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_lncc_clidengo26chikungunya.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_nus_nus-cerm.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_emap_epidematicos_prophet_fixed.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_procc_bb_model.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_purdue_neuralearth.csv.gz'),
 PosixPath('predictions/forecast_chik_state_mosqlimate-ai-competitor.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_emap_lstm.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_emap_xgbsillas.csv.gz'),
 PosixPath('predictions/forecast_chik_state_DS-OKSTATE-2026.csv.gz'),
 PosixPath('predictions/forecast_chik_state_3rd_imdc_lncc_surge_model26_chikungunya.csv.gz')]

In [13]:
print(len(arquivos_encontrados))

12

In [15]:
list_dfs = []

for arq in arquivos_encontrados:

    df_ = pd.read_csv(arq)
    df_.date = pd.to_datetime(df_.date)
    df_['model'] = str(arq)[32:-7]

    df_ = df_.loc[(df_.date>= pd.to_datetime(Week(2026, 41).startdate())) & (df_.date<= pd.to_datetime(Week(2027, 40).startdate()))]

    list_dfs.append(df_)


df_end = pd.concat(list_dfs, ignore_index = True)

df_end.to_csv(f'./predictions/forecast_all_models_{label[9:]}.csv.gz')


df_end.head()

,date,lower_95,lower_90,lower_80,lower_50,pred,upper_50,upper_80,upper_90,upper_95,adm_1,id,validation,model
0,2026-10-11,0.200655,0.519182,0.965134,2.225290,3.166690,5.676564,8.080002,9.462498,11.961388,12,13308,Forecast,3rd_imdc_emap_epidematicos_sarimax_fixed
1,2026-10-18,0.000000,0.084189,0.517639,1.488684,2.805839,4.860114,8.043318,10.547137,14.231962,12,13308,Forecast,3rd_imdc_emap_epidematicos_sarimax_fixed
2,2026-10-25,0.000000,0.000532,0.309755,1.096067,2.452235,5.063127,8.367789,12.152720,16.359749,12,13308,Forecast,3rd_imdc_emap_epidematicos_sarimax_fixed
3,2026-11-01,0.000000,0.000000,0.049297,0.803332,2.283912,4.719045,8.782080,13.205769,17.227440,12,13308,Forecast,3rd_imdc_emap_epidematicos_sarimax_fixed
4,2026-11-08,0.000000,0.000000,0.000000,0.620797,2.063121,4.641258,8.815452,12.637288,16.683337,12,13308,Forecast,3rd_imdc_emap_epidematicos_sarimax_fixed

In [ ]:
3rd_imdc_lncc_surge_model26_chikungunya

In [16]:
df_end.model.unique()

<ArrowStringArray>
['3rd_imdc_emap_epidematicos_sarimax_fixed',
          '3rd_imdc_lncc_ARp26_chikungunya',
      '3rd_imdc_lncc_clidengo26chikungunya',
                    '3rd_imdc_nus_nus-cerm',
 '3rd_imdc_emap_epidematicos_prophet_fixed',
                  '3rd_imdc_procc_bb_model',
              '3rd_imdc_purdue_neuralearth',
                 'mosqlimate-ai-competitor',
                       '3rd_imdc_emap_lstm',
                  '3rd_imdc_emap_xgbsillas',
                          'DS-OKSTATE-2026',
  '3rd_imdc_lncc_surge_model26_chikungunya']
Length: 12, dtype: str

In [ ]:
df_ = pd.read_csv("predictions/forecast_dengue_state_3rd_imdc_afya_ric.csv.gz")
df_.head()

,date,lower_95,lower_90,lower_80,lower_50,pred,upper_50,upper_80,upper_90,upper_95,adm_1,id,validation
0,2026-06-07,0.0,0.0,0.0,344.0,775.0,1206.0,1594.0,1826.0,2028.0,33,14168,Forecast
1,2026-06-14,0.0,0.0,0.0,0.0,652.0,1406.0,2084.0,2490.0,2843.0,33,14168,Forecast
2,2026-06-21,0.0,0.0,0.0,0.0,547.0,1604.0,2556.0,3125.0,3619.0,33,14168,Forecast
3,2026-06-28,0.0,0.0,0.0,0.0,336.0,1669.0,2869.0,3587.0,4210.0,33,14168,Forecast
4,2026-07-05,0.0,0.0,0.0,0.0,328.0,1912.0,3338.0,4191.0,4931.0,33,14168,Forecast