Notebook to calculate total cases, peak height, peak week, and $R_0$ for each model's predictions.

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as st
import mosqlient as mosq
from epiweeks import Week
from aux_func import get_data
from analysis import * 
import matplotlib.pyplot as plt 
import seaborn as sns 
from mosqlient.prediction_optimize import get_df_pars_ls

In [2]:
code_to_state = {33: 'RJ', 32: 'ES', 41: 'PR', 23: 'CE', 21: 'MA',
 31: 'MG', 42: 'SC', 26: 'PE', 25: 'PB', 24: 'RN', 22: 'PI', 27: 'AL',
 28: 'SE', 35: 'SP', 43: 'RS', 15: 'PA', 16: 'AP', 14: 'RR',  11: 'RO',
 13: 'AM', 12: 'AC', 51: 'MT', 50: 'MS', 52: 'GO', 17: 'TO', 53: 'DF',
 29: 'BA'}

state_to_code = {value: key for key, value in code_to_state.items()}

geo_dengue = [2931350,2933307,2302503,3119401,
              3549805,3541406,1200401,1200203,
              1716109,4113700,4103701,4104808,
              5201405,5102637,5215231]

geo_chik = [2211001,2931350,3143302,3119401,
            1721000,1716109,4104808,4219507,
            5103403,5102637]

In [19]:
challenge = 'dengue_city'
col_region = 'adm_2'

In [4]:
df_dengue_state  = get_data(challenge)
df_dengue_state.date = pd.to_datetime(df_dengue_state.date)

In [5]:
df_preds = pd.read_csv(f'./predictions/predictions_all_models_{challenge}.csv.gz', index_col = 'Unnamed: 0')
df_preds.date = pd.to_datetime(df_preds.date)

df_preds.model.unique()

<ArrowStringArray>
['3rd_imdc_emap_epidematicos_sarimax_fixed',
                    '3rd_imdc_nus_nus-cerm',
                  '3rd_imdc_emap_lstm_muni',
                  '3rd_imdc_emap_xgbsillas',
 '3rd_imdc_emap_epidematicos_prophet_fixed',
              '3rd_imdc_purdue_neuralearth']
Length: 6, dtype: str

In [6]:


df_preds = df_preds.loc[df_preds.model.isin([                        '3rd_imdc_emap_epidematicos_sarimax_fixed',
                       '3rd_imdc_emap_epidematicos_prophet_fixed', '3rd_imdc_bsc_ghr'

                                             ])]

#df_preds = df_preds.loc[df_preds.model.isin([
#                       'mosqlimate-ai-competitor'
#                                             ])]

df_preds.head()

,date,lower_95,lower_90,lower_80,lower_50,pred,upper_50,upper_80,upper_90,upper_95,adm_2,id,validation,wis,model
0,2022-10-09,25.725779,40.048709,51.521559,71.846609,97.558066,139.275377,213.218291,275.721368,339.686145,2211001,13242,1,24.86,3rd_imdc_emap_epidematicos_sarimax_fixed
1,2022-10-16,21.174558,30.370234,38.414624,60.509652,89.745516,132.868671,200.665062,269.239226,320.662330,2211001,13242,1,24.86,3rd_imdc_emap_epidematicos_sarimax_fixed
2,2022-10-23,14.875249,21.505565,30.849059,50.225775,80.677850,131.207909,202.387555,268.993745,326.896074,2211001,13242,1,24.86,3rd_imdc_emap_epidematicos_sarimax_fixed
3,2022-10-30,12.338729,17.735987,25.616908,43.639132,74.259948,124.076144,209.722579,278.453083,352.552289,2211001,13242,1,24.86,3rd_imdc_emap_epidematicos_sarimax_fixed
4,2022-11-06,10.319616,14.082060,20.680341,38.656206,68.720645,126.590559,229.344991,326.112375,430.224896,2211001,13242,1,24.86,3rd_imdc_emap_epidematicos_sarimax_fixed

In [7]:
df_preds.model.unique()

<ArrowStringArray>
['3rd_imdc_emap_epidematicos_sarimax_fixed', '3rd_imdc_emap_epidematicos_prophet_fixed']
Length: 2, dtype: str

In [10]:
df_dengue_state = df_dengue_state.merge(
        df_preds[["date", col_region, "validation"]].drop_duplicates(
                subset=["date", col_region, "validation"],
                keep="first"
            ), on=["date", col_region]
    )

df_dengue_state.head()

        date    adm_2  casos  validation
0 2022-10-09  2211001      2           1
1 2022-10-09  1721000      3           1
2 2022-10-09  4104808      0           1
3 2022-10-09  5102637      0           1
4 2022-10-09  3143302      1           1

In [11]:
def process_single_combination(df_preds, df_dengue_state,col_region, region, model, validation, n_paths=1000, n_samples=100, seed=0):
    """
    Processa a simulação e métricas para uma única combinação de modelo e validação.
    """
    rng = np.random.default_rng(seed)
    
    # 1. Filtragem e preparação de parâmetros
    df_preds_m = df_preds.loc[(df_preds.model == model) & (df_preds[col_region]== region)]
    #print(df_preds_m.shape)
    if df_preds_m.empty:
        return None  # Retorna None se não houver dados para essa combinação
        
    df_pars = get_df_pars_ls(df_preds_m)
    df_pars.loc[(df_pars.mu <= 0) | (df_pars.mu.isna()), 'mu'] = 0.1
    df_pars.loc[(df_pars.sigma <= 0) | (df_pars.sigma.isna()), 'sigma'] = 0.1

    # 2. Estimativa de Rho e Marginais
    df_rho_input = df_pars.loc[(df_pars['validation'] == validation - 1)].merge(
        df_dengue_state, on=['date', col_region, 'validation'], how='left'
    )
    rho = estimate_rho(df_rho_input)
    marginals_uf = build_marginals(df_pars, col_region, region, validation)

    # 3. Geração das trajetórias (paths)
    paths = np.vstack([
        sample_path(marginals_uf, rho, random_state=rng)
        for _ in range(n_paths)
    ])

    # 4. Cálculo das métricas baseadas em todas as trajetórias
    season_total = paths.sum(axis=1)
    season_peak = paths.max(axis=1)

    # 5. Amostragem para ajuste da curva de Richards
    indices_aleatorios = rng.choice(paths.shape[0], size=n_samples, replace=False)
    amostras_paths = paths[indices_aleatorios, :]

    r0_dist = []
    pico_dist = []
    t_ini_dist = []
    max_c_dist = []
    richards_curves = []

    for i, path in enumerate(amostras_paths):
        r0_i, pico_i, t_ini_i, max_c_i, richards = otim_single_path(path)
        r0_dist.append(r0_i)
        pico_dist.append(pico_i)
        t_ini_dist.append(t_ini_i)
        max_c_dist.append(max_c_i)

        df_curve = pd.DataFrame({
            "sample": i,
            "week": np.arange(len(richards)),
            "richards": richards
        })

        richards_curves.append(df_curve)

    richards_df = pd.concat(richards_curves, ignore_index=True)

    r0_dist = np.array(r0_dist)
    pico_dist = np.array(pico_dist)
    t_ini_dist = np.array(t_ini_dist)
    max_c_dist = np.array(max_c_dist)

    # 6. Consolidação dos resultados em um dicionário de intervalos
    metrics = {
        'model': model,
        'validation': validation,
        col_region: region
    }
    
    # Dicionário mapeando o nome da métrica para o seu array de distribuição
    distributions = {
        'season_total': season_total,
        'season_peak': season_peak,
        'r0_dist': r0_dist,
        'pico_dist': pico_dist, 
        't_ini_dist': t_ini_dist, 
        'max_c_dist': max_c_dist
    }
    
    # Calcula os quantis automaticamente para cada métrica
    for name, dist in distributions.items():
        lo, med, hi = np.quantile(dist, [0.025, 0.5, 0.975])
        metrics[f'{name}_p25'] = lo
        metrics[f'{name}_p50'] = med
        metrics[f'{name}_p975'] = hi


    # Salva os resultados: 
    table_suffix = f"{region}_{model}_{validation}_{challenge}".replace("-", "_")

    df_pars.to_csv(f'./samples/pars_{table_suffix}.csv.gz', index = False)

    df_paths = (
        pd.DataFrame(paths)
        .reset_index(names="path")
        .melt(
            id_vars="path",
            var_name="week",
            value_name="cases"
        )
    )

    df_paths.to_csv(
        f"./samples/paths_{table_suffix}.csv.gz",
        index=False
    )

    # curvas de Richards
    richards_df.to_csv(
        f"./samples/richards_{table_suffix}.csv.gz",
        index=False
    )

    return metrics

In [12]:
def run_pipeline(df_preds, df_dengue_state, col_region, region, models_list, validations_list):
    """
    Executa o loop por todos os modelos e validações e retorna um DataFrame consolidado.
    """
    results = []
    
    for model in models_list:
        for validation in validations_list:
            #print(f"Processando: Modelo={model} | Validation={validation}...")
            try:
                res = process_single_combination(df_preds, df_dengue_state, col_region, region, model, validation)
                if res is not None:
                    results.append(res)
            except Exception as e:
                print(f"Erro ao processar Modelo={model}, Validation={validation}: {e}, {col_region}: {region}")
                continue
                
    # Transforma a lista de dicionários em um DataFrame estruturado
    df_results = pd.DataFrame(results)
    return df_results

In [13]:
%%time
# Listas de modelos e validações que você quer rodar
lista_modelos = df_preds.model.unique()
lista_validations = [2,3,4]

regions = df_preds[col_region].unique()


df_all_adm = pd.DataFrame()

for region_alvo in regions: 

    # Executa o pipeline
    df_final_resultados = run_pipeline(df_preds, df_dengue_state, col_region, region_alvo, lista_modelos, lista_validations)

    # Salva os resultados em um arquivo
    df_all_adm = pd.concat([df_all_adm, df_final_resultados], ignore_index=True) 


df_all_adm.head()

CPU times: user 9min 40s, sys: 111 ms, total: 9min 40s
Wall time: 9min 40s

,model,validation,adm_2,season_total_p25,season_total_p50,season_total_p975,season_peak_p25,season_peak_p50,season_peak_p975,r0_dist_p25,...,r0_dist_p975,pico_dist_p25,pico_dist_p50,pico_dist_p975,t_ini_dist_p25,t_ini_dist_p50,t_ini_dist_p975,max_c_dist_p25,max_c_dist_p50,max_c_dist_p975
0,3rd_imdc_emap_epidematicos_sarimax_fixed,2,2211001,381.464636,1613.638259,12381.772392,44.972886,267.578159,6106.163482,1.064022,...,1.952083,5.000000,23.396030,35.0,1.0,1.0,13.000,9.760975,73.756130,532.926132
1,3rd_imdc_emap_epidematicos_sarimax_fixed,3,2211001,201.663588,946.745091,8536.324275,24.223100,192.430741,4003.407359,1.070029,...,2.615466,5.000000,23.714393,35.0,1.0,1.0,21.050,4.806138,45.428177,694.884365
2,3rd_imdc_emap_epidematicos_sarimax_fixed,4,2211001,154.139660,830.216915,7932.088874,25.237852,227.709184,4234.469711,1.096198,...,3.643110,9.552109,29.839399,35.0,1.0,1.0,27.100,4.415391,23.944204,882.230425
3,3rd_imdc_emap_epidematicos_prophet_fixed,2,2211001,89.874558,949.489398,11328.625374,11.606189,145.086536,2217.695079,1.087341,...,2.580918,18.413373,27.266752,35.0,1.0,11.0,22.525,7.374977,87.824400,1415.017667
4,3rd_imdc_emap_epidematicos_prophet_fixed,3,2211001,376.041822,1079.472835,4802.737693,57.917277,290.268189,3185.732185,1.103244,...,4.124880,19.818793,27.954007,35.0,1.0,9.0,23.525,16.067732,70.869692,860.816064

In [14]:
df_all_adm.model.unique()

<ArrowStringArray>
['3rd_imdc_emap_epidematicos_sarimax_fixed', '3rd_imdc_emap_epidematicos_prophet_fixed']
Length: 2, dtype: str

In [20]:
df_old = pd.read_csv(f'predictions/new_metrics_{challenge}_new.csv.gz')

#df_old['model'] = '3rd' + df_old.model.astype(str)

df_old = df_old.loc[~df_old.model.isin([ 
                                                '3rd_imdc_emap_epidematicos_sarimax_state'
                                                ])]
#df_old = df_old.loc[~df_old.model.isin(['3rd_imdc_emap_epidematicos_prophet', 
#                                                '3rd_imdc_emap_epidematicos_sarimax',
#                                                '3rd_imdc_emap_epidematicos_sarimax_muni',
#                                                '3rd_imdc_bsc_ghr'])]

df_old.head()

,model,validation,adm_2,season_total_p25,season_total_p50,season_total_p975,season_peak_p25,season_peak_p50,season_peak_p975,r0_dist_p25,...,r0_dist_p975,pico_dist_p25,pico_dist_p50,pico_dist_p975,t_ini_dist_p25,t_ini_dist_p50,t_ini_dist_p975,max_c_dist_p25,max_c_dist_p50,max_c_dist_p975
0,3rd_imdc_fgv_pattern-blue,2,2933307,733.909479,1885.217757,5779.345512,102.064520,424.618497,2774.845948,1.093611,...,2.483450,19.937389,26.636748,35.000000,1.0,1.0,22.050,26.576949,108.947387,737.993226
1,3rd_imdc_fgv_pattern-blue,3,2933307,26.696225,663.509646,14658.005350,1.446443,35.322667,728.108614,1.155805,...,1.601317,25.994597,26.212592,26.849500,1.0,3.0,4.000,5.168774,35.858010,985.399530
2,3rd_imdc_fgv_pattern-blue,4,2933307,28.478913,669.702784,12714.789369,1.542586,35.587938,626.672167,1.153066,...,1.613907,25.956333,26.295624,26.869531,1.0,3.0,4.525,1.366005,29.999773,518.939225
3,3rd_imdc_emap_lstm_muni,2,2933307,418.685033,1503.722946,6778.437599,63.409813,324.554007,3012.014323,1.061563,...,2.757746,12.042234,27.559206,35.000000,1.0,5.0,23.000,16.251780,87.164511,697.228118
4,3rd_imdc_emap_lstm_muni,3,2933307,16.006771,737.750230,42054.270271,3.011120,73.681697,3145.717538,1.195574,...,1.734411,22.242303,25.958029,28.205975,1.0,7.0,10.000,4.843071,47.411474,3534.781850

In [21]:
df_old.model.unique()

<ArrowStringArray>
[                                     '3rd_imdc_fgv_pattern-blue',
                                        '3rd_imdc_emap_lstm_muni',
                                    '3rd_imdc_purdue_neuralearth',
                                          '3rd_imdc_nus_nus-cerm',
 '3rd_imdc_universidad_del_valle_grupo_modelamiento_datos_dengue',
                                        '3rd_imdc_emap_xgbsillas',
                                         '3rd_imdc_unesp_recogna',
                                        '3rd_imdc_isi_isi-dengue',
                       '3rd_imdc_emap_epidematicos_prophet_fixed',
                       '3rd_imdc_emap_epidematicos_sarimax_fixed']
Length: 10, dtype: str

In [33]:
df_end = pd.concat([df_old, df_all_adm], ignore_index=True)

df_end.head()

,model,validation,state,season_total_p25,season_total_p50,season_total_p975,season_peak_p25,season_peak_p50,season_peak_p975,r0_dist_p25,...,pico_dist_p25,pico_dist_p50,pico_dist_p975,t_ini_dist_p25,t_ini_dist_p50,t_ini_dist_p975,max_c_dist_p25,max_c_dist_p50,max_c_dist_p975,adm_1
0,3rd_imdc_lncc_surge_model26_chikungunya,2,11.0,1382.094707,1520.900685,1667.579712,121.570939,143.834072,172.606994,1.932908,...,25.891381,26.175782,26.418224,12.0,13.0,14.0,116.375596,132.279998,149.651394,NaN
1,3rd_imdc_lncc_surge_model26_chikungunya,3,11.0,609.137207,1208.376690,2733.672292,91.371803,280.828946,1367.065478,1.176346,...,22.234417,25.034667,28.989796,5.0,13.0,21.0,41.909099,123.976278,597.850427,NaN
2,3rd_imdc_lncc_clidengo26chikungunya,2,11.0,59.925595,66.499984,74.991226,1.779697,2.525093,4.012866,1.242731,...,22.896091,25.529129,28.935903,1.0,1.0,1.0,1.499136,1.683797,1.951129,NaN
3,3rd_imdc_lncc_clidengo26chikungunya,3,11.0,64.563524,74.311434,87.484991,2.285402,3.472361,6.405862,1.248660,...,20.535043,23.929665,27.928083,1.0,1.0,1.0,1.663435,1.939856,2.453540,NaN
4,3rd_imdc_lncc_clidengo26chikungunya,4,11.0,41.080156,77.253158,162.232047,0.921282,2.235753,8.062171,1.109373,...,15.176524,24.325372,34.386213,1.0,1.0,1.0,1.042707,1.850575,5.219166,NaN

In [34]:
df_end.model.unique()

<ArrowStringArray>
[ '3rd_imdc_lncc_surge_model26_chikungunya',
      '3rd_imdc_lncc_clidengo26chikungunya',
                       '3rd_imdc_emap_lstm',
          '3rd_imdc_lncc_ARp26_chikungunya',
                  '3rd_imdc_emap_xgbsillas',
                          'DS-OKSTATE-2026',
              '3rd_imdc_purdue_neuralearth',
                    '3rd_imdc_nus_nus-cerm',
                  '3rd_imdc_procc_bb_model',
 '3rd_imdc_emap_epidematicos_prophet_fixed',
 '3rd_imdc_emap_epidematicos_sarimax_fixed',
                 'mosqlimate-ai-competitor']
Length: 12, dtype: str

In [36]:
df_end.to_csv(f'predictions/new_metrics_{challenge}_new.csv.gz', index = False)