In [1]:
import numpy as np 
import pandas as pd 
from aux_func import code_to_state, estado_para_regiao

In [3]:
challenge = 'dengue_state'

In [4]:
df_ratio = pd.read_csv(f'predictions/rank_ratio_{challenge}.csv.gz')

df_ratio.head()

,model,adm_1,validation,wis,wis_baseline,wis_ratio,region
0,3rd_imdc_-unifesp-_-4mosqueteiras-,11,1,205.38,101.894535,2.015613,North
1,3rd_imdc_-unifesp-_-4mosqueteiras-,11,2,68.46,31.277812,2.188772,North
2,3rd_imdc_-unifesp-_-4mosqueteiras-,11,3,30.97,24.740000,1.251819,North
3,3rd_imdc_-unifesp-_-4mosqueteiras-,11,4,42.33,26.550000,1.594350,North
4,3rd_imdc_-unifesp-_-4mosqueteiras-,12,1,37.72,30.964984,1.218150,North

In [7]:
df_ratio.groupby(['region', 'model'])[['wis_ratio']].median().reset_index()

        region                                              model  wis_ratio
0      Midwest                 3rd_imdc_-unifesp-_-4mosqueteiras-   1.734304
1      Midwest                                  3rd_imdc_afya_ric   1.535346
2      Midwest                                   3rd_imdc_bsc_ghr   0.910805
3      Midwest                  3rd_imdc_ceri_returnoftheforecast   1.328840
4      Midwest                          3rd_imdc_cornell_bentolab   0.996672
..         ...                                                ...        ...
130  Southeast                            3rd_imdc_rki_rki_zki_ph   0.896940
131  Southeast                   3rd_imdc_rki_rki_zki_ph_lstm_geo   1.126354
132  Southeast                             3rd_imdc_unesp_recogna   1.891979
133  Southeast  3rd_imdc_universidad_del_valle_grupo_modelamie...   1.075149
134  Southeast                                    DS-OKSTATE-2026   1.906393

[135 rows x 3 columns]

In [8]:
df_best = (
    df_ratio
    .groupby(["region", "model"], as_index=False)["wis_ratio"]
    .median()
    .sort_values("wis_ratio")
    .groupby("region", as_index=False)
    .first()
)
df_best

      region                                     model  wis_ratio
0    Midwest                        3rd_imdc_emap_lstm   0.860435
1      North               3rd_imdc_purdue_neuralearth   0.929145
2  Northeast  3rd_imdc_emap_epidematicos_sarimax_state   0.775573
3      South        3rd_imdc_emap_epidematicos_prophet   0.611302
4  Southeast               3rd_imdc_purdue_neuralearth   0.822490