In [1]:
import numpy as np
import pandas as pd
import mosqlient as mosq
from epiweeks import Week

In [4]:
!pip show mosqlient

Name: mosqlient
Version: 2.5.1
Summary: client library for the mosqlimate client library
Home-page: https://github.com/Mosqlimate-project/mosqlimate-client
Author: Flávio Codeço Coelho
Author-email: fccoelho@gmail.com
License: GPLv3
Location: /home/eduardocorrea/miniforge3/envs/torch311/lib/python3.11/site-packages
Requires: aiohttp, cffi, epiweeks, loguru, nest-asyncio, numpy, pandas, pydantic, requests, seaborn, tabulate, tqdm, types-requests, vl-convert-python
Required-by:

In [2]:
api_key = 'eduardocorrearaujo:00566e8d-b64b-44a3-83b7-b50a086096e0'

In [3]:
preds = mosq.get_predictions(api_key = api_key, imdc_year='2025')

df_info = pd.DataFrame([
    {   "pred": pred, 
        "model_name": pred.model.repository,
        "id": pred.id, 
        "adm_1": pred.adm_1,
        "start": pred.start,
        "end": pred.end,
        "wis": pred.scores.get("wis")
        if pred.scores is not None else None,
        "published": pred.published }
    for pred in preds
])

df_info = df_info.loc[df_info.published == True]

# removendo as duplicatas mantendo a previsão com o maior id

df_info = (
            df_info.sort_values("id")
            .drop_duplicates(
                subset=["model_name", "adm_1", "start", "end"],
                keep="last"
            )
        )

df_info.head()

100%|██████████| 7/7 [00:07<00:00,  1.08s/requests]

,pred,model_name,id,adm_1,start,end,wis,published
0,"{""id"":3,""model"":{""id"":20,""repository"":""hadrian...",hadrianang/imperial-mosqlimate-sprint2025,3,14,2022-10-09,2023-10-01,2.51,True
1,"{""id"":6,""model"":{""id"":20,""repository"":""hadrian...",hadrianang/imperial-mosqlimate-sprint2025,6,25,2023-10-08,2024-09-29,97.11,True
2,"{""id"":7,""model"":{""id"":13,""repository"":""rick011...",rick0110/Preditores_da_Picada,7,28,2023-10-08,2024-09-29,197.75,True
3,"{""id"":8,""model"":{""id"":20,""repository"":""hadrian...",hadrianang/imperial-mosqlimate-sprint2025,8,24,2024-10-06,2025-09-28,60.83,True
4,"{""id"":11,""model"":{""id"":16,""repository"":""lacidu...",lacidufrn/infodengue_sprint_2025,11,23,2024-10-06,2025-09-28,77.37,True

In [6]:
df_info.model_name.value_counts()

model_name
rick0110/Preditores_da_Picada                 108
anabento/DengueSprint_Cornell-PEH             108
marciomacielbastos/MosqlimateSprint2025       108
americocunhajr/D-FENSE                        108
lsbastos/sprint2025                           108
haridas-das/DS_OKSTATE_2025                   108
eduardocorrearaujo/dengue-oracle              108
americocunhajr/D-FENSE-1                      108
americocunhajr/D-FENSE-2                      108
eduardocorrearaujo/dengue-oracle-1            108
hadrianang/imperial-mosqlimate-sprint2025     104
chlobular/ghr-imdc-2025                       104
davibarreira/jbd-mosqlimate-sprint            104
DavideNicola/ISI_Dengue_Model                 104
graeme-dor/dengue-sprint-2025                  84
ChenXiang1998/2025-Infodengue-Sprint           81
americocunhajr/D-FENSE-3                       81
lacidufrn/infodengue_sprint_2025               78
DiogoParreira/ZKI-PH                           78
eduardocorrearaujo/2nd_IMDC_sprint_results     27
eduardocorrearaujo/sprint-template              1
Name: count, dtype: int64

In [7]:
df_info.loc[df_info.model_name == 'graeme-dor/dengue-sprint-2025'].adm_1.value_counts()

adm_1
22    4
41    4
33    4
24    4
14    4
43    4
28    4
17    4
31    4
29    3
16    3
23    3
11    3
32    3
21    3
35    3
25    3
51    3
12    3
27    3
26    3
13    2
53    2
52    2
50    2
15    2
42    2
Name: count, dtype: int64

In [8]:
def load_preds_single_model(api_key = api_key, model_name = 'str'): 

    preds = mosq.get_predictions(api_key = api_key, model_name= model_name)

    df_info = pd.DataFrame([
        {   "pred": pred, 
            "model_name": pred.model.repository,
            "id": pred.id, 
            "adm_1": pred.adm_1,
            "start": pred.start,
            "end": pred.end,
            "wis": pred.scores.get("wis")
            if pred.scores is not None else None,
            "published": pred.published }
        for pred in preds
    ])

    df_info = df_info.loc[df_info.published == True]

    # removendo as duplicatas mantendo a previsão com o maior id

    df_info = (
            df_info.sort_values("id")
            .drop_duplicates(
                subset=["adm_1", "start", "end"],
                keep="last"
            )
        )


    return df_info

In [15]:
df_graeme = load_preds_single_model(api_key = api_key, model_name =  'D-FENSE-3')

df_graeme.head()

,pred,model_name,id,adm_1,start,end,wis,published
66,"{""id"":4836,""model"":{""id"":36,""repository"":""amer...",americocunhajr/D-FENSE-3,4836,53,2022-10-09,2023-10-01,125.91,True
67,"{""id"":4837,""model"":{""id"":36,""repository"":""amer...",americocunhajr/D-FENSE-3,4837,28,2022-10-09,2023-10-01,35.64,True
68,"{""id"":4838,""model"":{""id"":36,""repository"":""amer...",americocunhajr/D-FENSE-3,4838,16,2023-10-08,2024-09-29,163.45,True
69,"{""id"":4839,""model"":{""id"":36,""repository"":""amer...",americocunhajr/D-FENSE-3,4839,53,2023-10-08,2024-09-29,3468.54,True
71,"{""id"":4841,""model"":{""id"":36,""repository"":""amer...",americocunhajr/D-FENSE-3,4841,16,2022-10-09,2023-10-01,7.70,True

In [14]:
df_graeme.loc[df_graeme.adm_1 == 42]

,pred,model_name,id,adm_1,start,end,wis,published
245,"{""id"":1530,""model"":{""id"":21,""repository"":""grae...",graeme-dor/dengue-sprint-2025,1530,42,2024-10-06,2025-09-28,329.68,True
357,"{""id"":3187,""model"":{""id"":21,""repository"":""grae...",graeme-dor/dengue-sprint-2025,3187,42,2025-10-05,2026-10-04,809.00,True

In [13]:
df_graeme.adm_1.shape

(84,)

In [16]:
df_graeme.adm_1.value_counts()

adm_1
53    3
28    3
16    3
52    3
23    3
29    3
43    3
41    3
33    3
32    3
24    3
42    3
50    3
51    3
26    3
31    3
12    3
35    3
15    3
11    3
27    3
21    3
14    3
17    3
22    3
25    3
13    3
Name: count, dtype: int64

In [10]:
preds = mosq.get_predictions(api_key = api_key, model_name= 'graeme-dor/dengue-sprint-2025')

preds

[]

In [ ]:
df_do = df_info.loc[df_info.model_name == 'eduardocorrearaujo/dengue-oracle']

df_do.adm_1.value_counts()[df_do.adm_1.value_counts() != 3]

adm_1
23    4
33    4
17    4
13    4
25    4
35    4
11    4
53    4
52    4
41    4
51    4
32    4
21    4
15    4
42    4
50    4
28    4
29    4
14    4
26    4
16    2
22    2
Name: count, dtype: int64

In [71]:
df_do.adm_1.value_counts()[df_do.adm_1.value_counts() == 3]

adm_1
12    3
31    3
27    3
43    3
24    3
Name: count, dtype: int64

In [ ]:
preds = mosq.get_predictions(api_key = api_key, imdc_year='2025')

In [60]:
df_info.loc[df_info.wis.isna()]

,pred,model_name,id,adm_1,start,end,wis,published
1593,"{""id"":1153,""model"":{""id"":4,""repository"":""eduar...",eduardocorrearaujo/sprint-template,1153,33,2022-10-22,2023-10-15,NaN,True

In [50]:
df_info.loc[df_info.id == 3328]

,pred,model_name,id,adm_1,start,end,wis
2112,"{""id"":3328,""model"":{""id"":21,""repository"":""grae...",graeme-dor/dengue-sprint-2025,3328,32,2025-10-05,2026-10-04,497.89

In [64]:
preds_model = mosq.get_predictions(api_key = api_key, 
                                   model_name = 'dengue-oracle', imdc_year='2025')


len(preds_model)

216

In [46]:
preds[12].model.repository

'rick0110/Preditores_da_Picada'

In [32]:
for i, pred in enumerate(preds):
    try:
        pred.scores['wis']
    except Exception as e:
        print(i, type(e).__name__, e)

13 KeyError 'wis'
15 KeyError 'wis'
17 KeyError 'wis'
30 KeyError 'wis'
33 KeyError 'wis'
37 KeyError 'wis'
51 KeyError 'wis'
66 KeyError 'wis'
67 KeyError 'wis'
77 KeyError 'wis'
79 KeyError 'wis'
87 KeyError 'wis'
92 KeyError 'wis'
114 KeyError 'wis'
115 KeyError 'wis'
117 KeyError 'wis'
120 KeyError 'wis'
139 KeyError 'wis'
143 KeyError 'wis'
144 KeyError 'wis'
166 KeyError 'wis'
168 KeyError 'wis'
170 KeyError 'wis'
172 KeyError 'wis'
177 KeyError 'wis'
196 KeyError 'wis'
198 KeyError 'wis'
199 KeyError 'wis'
205 KeyError 'wis'
220 KeyError 'wis'
222 KeyError 'wis'
223 KeyError 'wis'
243 KeyError 'wis'
248 KeyError 'wis'
249 KeyError 'wis'
253 KeyError 'wis'
264 KeyError 'wis'
273 KeyError 'wis'
283 KeyError 'wis'
291 KeyError 'wis'
292 KeyError 'wis'
297 KeyError 'wis'
304 KeyError 'wis'
316 KeyError 'wis'
331 KeyError 'wis'
415 KeyError 'wis'
461 KeyError 'wis'
486 KeyError 'wis'
552 KeyError 'wis'
613 KeyError 'wis'
697 KeyError 'wis'
717 KeyError 'wis'
726 KeyError 'wis'
750 KeyError 'wis'
779 KeyError 'wis'
865 KeyError 'wis'
874 KeyError 'wis'
883 KeyError 'wis'
884 KeyError 'wis'
893 KeyError 'wis'
912 KeyError 'wis'
942 KeyError 'wis'
976 KeyError 'wis'
981 KeyError 'wis'
996 KeyError 'wis'
1025 KeyError 'wis'
1087 KeyError 'wis'
1112 KeyError 'wis'
1119 KeyError 'wis'
1131 KeyError 'wis'
1207 KeyError 'wis'
1222 KeyError 'wis'
1279 KeyError 'wis'
1363 KeyError 'wis'
1391 KeyError 'wis'
1431 KeyError 'wis'
1459 KeyError 'wis'
1464 KeyError 'wis'
1467 KeyError 'wis'
1491 KeyError 'wis'
1502 KeyError 'wis'
1516 KeyError 'wis'
1545 KeyError 'wis'
1556 KeyError 'wis'
1571 KeyError 'wis'
1577 KeyError 'wis'
1593 KeyError 'wis'
1640 KeyError 'wis'
1648 KeyError 'wis'
1669 KeyError 'wis'
1686 KeyError 'wis'
1732 KeyError 'wis'
1733 KeyError 'wis'
1808 KeyError 'wis'
1863 KeyError 'wis'
1909 KeyError 'wis'
1931 KeyError 'wis'
1936 KeyError 'wis'
1964 KeyError 'wis'
1977 KeyError 'wis'
1981 KeyError 'wis'
1989 KeyError 'wis'
2015 KeyError 'wis'
2017 KeyError 'wis'
2028 KeyError 'wis'
2037 KeyError 'wis'
2055 KeyError 'wis'
2071 KeyError 'wis'
2093 KeyError 'wis'
2123 KeyError 'wis'
2217 KeyError 'wis'
2221 KeyError 'wis'
2258 KeyError 'wis'
2298 KeyError 'wis'
2315 KeyError 'wis'
2356 KeyError 'wis'

In [23]:
vars(preds[0])

{'client': <mosqlient.client.Mosqlient at 0x795ad95b8ad0>,
 'model': hadrianang/imperial-mosqlimate-sprint2025}

In [19]:
preds[0]

Prediction <3>

In [25]:
preds[0].scores['wis']

2.51

In [9]:
preds[0].start

datetime.date(2022, 10, 9)

In [12]:
preds[0].model

hadrianang/imperial-mosqlimate-sprint2025

In [17]:
preds[0].id

3