In [3]:
import pandas as pd
from epiweeks import Week

In [5]:
df_old = pd.read_csv('chik_state.csv.gz')
df_old.date = pd.to_datetime(df_old.date)
df_old.head()

        date  adm_1  casos
0 2013-12-29     11      0
1 2013-12-29     12      0
2 2013-12-29     13      0
3 2013-12-29     14      0
4 2013-12-29     15      0

In [9]:
df_old.loc[df_old.date == pd.to_datetime(Week(2023,24).startdate())]

            date  adm_1  casos
13311 2023-06-11     11      1
13312 2023-06-11     12      0
13313 2023-06-11     13      9
13314 2023-06-11     14      3
13315 2023-06-11     15     19
13316 2023-06-11     16      0
13317 2023-06-11     17     54
13318 2023-06-11     21     77
13319 2023-06-11     22     92
13320 2023-06-11     23    110
13321 2023-06-11     24     37
13322 2023-06-11     25     39
13323 2023-06-11     26     68
13324 2023-06-11     27     20
13325 2023-06-11     28     56
13326 2023-06-11     29    449
13327 2023-06-11     31   1485
13328 2023-06-11     32      1
13329 2023-06-11     33     46
13330 2023-06-11     35     66
13331 2023-06-11     41     34
13332 2023-06-11     42      9
13333 2023-06-11     43      2
13334 2023-06-11     50     86
13335 2023-06-11     51      5
13336 2023-06-11     52     74
13337 2023-06-11     53     16

In [11]:
df_new = pd.read_csv('../../imdc_2026/chikungunya_update.csv.gz')
df_new = df_new.groupby(['date', 'uf_code'])[['casos']].sum().reset_index().rename(columns = {'uf_code': 'adm_1'})
df_new.date = pd.to_datetime(df_new.date)
df_new.loc[df_new.date>='2023-06-11']

           date  adm_1  casos
27   2023-06-11     11      1
28   2023-06-11     12      0
29   2023-06-11     13      8
30   2023-06-11     14      2
31   2023-06-11     15     19
...         ...    ...    ...
4693 2026-09-27     43      0
4694 2026-09-27     50      0
4695 2026-09-27     51      0
4696 2026-09-27     52      0
4697 2026-09-27     53      0

[4671 rows x 3 columns]

In [12]:
df_end = pd.concat([df_old.loc[df_old.date <= pd.to_datetime(Week(2023,24).startdate())], df_new.loc[df_new.date>'2023-06-11']])

In [13]:
df_end.to_csv('chik_state.csv.gz', index = False)

In [9]:
df_new.to_csv('dengue_state.csv.gz', index = False)

In [10]:
df = pd.read_csv('dengue_state.csv.gz')
df.head()

         date  adm_1  casos
0  2010-01-03     11   2456
1  2010-01-03     12    760
2  2010-01-03     13    155
3  2010-01-03     14     25
4  2010-01-03     15    115